imports:
    - { resource: config.yml }

monolog:
    handlers:
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug

doctrine:
    dbal:
        url: "%env(CLEARDB_DATABASE_URL)%"

nelmio_cors:
    defaults:
        allow_origin:   ["%env(CROSS_ALLOW_ORIGIN)%"]