services:
    AppBundle\Service\HappinessLevelStatistics:
        class: AppBundle\Service\HappinessLevelStatistics
        autowire: true

    AppBundle\Repository\HappinessLevelRepository:
          class: Doctrine\ORM\EntityRepository
          factory: ['@doctrine.orm.default_entity_manager', getRepository]
          arguments:
              - AppBundle\Entity\HappinessLevel